version: "3.9"
services:
  api:
    command: sh -c "python -m debugpy --listen 0.0.0.0:5678 manage.py runserver 0.0.0.0:8000 --nothreading"
    ports:
      - "8000:8000"
      - "5678:5678"
    volumes:
      - ./api:/app
    environment:
      DJANGO_DEBUG: "1"