# docker-compose.yml (backend + Postgres only)
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "9220:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: ./api
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./api:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432

volumes:
  postgres_data: